import { useState, useCallback } from 'react';
import {
  HighSchoolSeries,
  BimesterNumber,
  Subject,
  TeacherTopic,
  CurriculumConfigInfo
} from '../types';
import { HIGH_SCHOOL_CURRICULUM_TEMPLATES } from '../data/curriculumTemplates';

export function useCurriculumTemplate() {
  const [selectedSeries, setSelectedSeries] = useState<HighSchoolSeries>('2nd');
  const [selectedBimester, setSelectedBimester] = useState<BimesterNumber>(2);
  const [markPreviousAsCompleted, setMarkPreviousAsCompleted] = useState<boolean>(true);

  /**
   * Generates a list of Subject objects based on series, bimester and markPrevious settings.
   */
  const generateSubjects = useCallback((
    series: HighSchoolSeries = selectedSeries,
    currentBimester: BimesterNumber = selectedBimester,
    markPrevious: boolean = markPreviousAsCompleted
  ): Subject[] => {
    const template = HIGH_SCHOOL_CURRICULUM_TEMPLATES[series] || HIGH_SCHOOL_CURRICULUM_TEMPLATES['2nd'];

    return template.subjects.map((subTemplate) => {
      const formattedTopics: TeacherTopic[] = subTemplate.topics.map((t) => {
        const isPastBimester = t.bimester < currentBimester;
        const taught = isPastBimester ? markPrevious : false;

        return {
          id: `top-${t.id}`,
          name: t.name,
          taught,
          taughtDate: taught ? new Date().toISOString().split('T')[0] : undefined,
          bimester: t.bimester
        };
      });

      return {
        id: `sub-${series}-${subTemplate.id}`,
        name: subTemplate.name,
        category: subTemplate.category,
        color: subTemplate.color,
        teacherName: 'Prof. Indicado',
        topics: formattedTopics,
        examScopeTopicIds: [],
        enabled: true,
        isCustom: false,
        weight: 3
      };
    });
  }, [selectedSeries, selectedBimester, markPreviousAsCompleted]);

  /**
   * Subdivides a parent subject into two (e.g. Física -> Física A e Física B)
   * and moves specified topicIds into the new subdivision subject.
   */
  const subdivideSubject = useCallback((
    subjects: Subject[],
    parentSubjectId: string,
    subdivisionName: string,
    topicIdsToMove: string[]
  ): Subject[] => {
    const parentIndex = subjects.findIndex((s) => s.id === parentSubjectId);
    if (parentIndex === -1) return subjects;

    const parentSub = subjects[parentIndex];

    // Filter topics: keep unselected topics in parent, move selected topics to subdivision
    const topicsToMove = parentSub.topics.filter((t) => topicIdsToMove.includes(t.id));
    const remainingTopicsInParent = parentSub.topics.filter((t) => !topicIdsToMove.includes(t.id));

    // Updated parent subject
    const updatedParent: Subject = {
      ...parentSub,
      topics: remainingTopicsInParent
    };

    // New subdivision subject
    const newSubdivision: Subject = {
      id: `subdiv-${Date.now()}`,
      name: subdivisionName.trim() || `${parentSub.name} - Módulo 2`,
      category: parentSub.category,
      color: parentSub.color,
      teacherName: parentSub.teacherName,
      topics: topicsToMove,
      examScopeTopicIds: [],
      enabled: true,
      isCustom: true,
      parentSubjectId: parentSub.id,
      weight: parentSub.weight
    };

    const newSubjectsList = [...subjects];
    newSubjectsList[parentIndex] = updatedParent;
    newSubjectsList.splice(parentIndex + 1, 0, newSubdivision);

    return newSubjectsList;
  }, []);

  /**
   * Helper to build curriculum config metadata object to save in student profile.
   */
  const getCurriculumConfigInfo = useCallback((): CurriculumConfigInfo => {
    return {
      series: selectedSeries,
      currentBimester: selectedBimester,
      markPreviousAsCompleted,
      autoGenerated: true,
      templateVersion: '1.0',
      updatedAt: new Date().toISOString()
    };
  }, [selectedSeries, selectedBimester, markPreviousAsCompleted]);

  return {
    selectedSeries,
    setSelectedSeries,
    selectedBimester,
    setSelectedBimester,
    markPreviousAsCompleted,
    setMarkPreviousAsCompleted,
    generateSubjects,
    subdivideSubject,
    getCurriculumConfigInfo
  };
}
