import React, { useState, useEffect } from 'react';
import { Subject, Evaluation, SchoolConfig, EvaluationType, StudentTaskItem, SpacedRevision } from '../types';
import { TopicSelector } from './TopicSelector';
import { generateExamPrepPlan } from '../lib/evaluations';
import { trackEvent } from '../lib/analytics';
import { X, Calendar, Calculator, Sparkles, CheckCircle2, BookOpen, Layers, Plus, Save } from 'lucide-react';

interface EvaluationFormModalProps {
  isOpen: boolean;
  onClose: () => void;
  subjects: Subject[];
  schoolConfig: SchoolConfig;
  initialEvaluation?: Evaluation | null;
  existingTasks: StudentTaskItem[];
  existingRevisions: SpacedRevision[];
  onSaveEvaluation: (
    evaluation: Evaluation,
    newTasks?: StudentTaskItem[],
    newRevisions?: SpacedRevision[]
  ) => void;
}

export const EvaluationFormModal: React.FC<EvaluationFormModalProps> = ({
  isOpen,
  onClose,
  subjects,
  schoolConfig,
  initialEvaluation,
  existingTasks,
  existingRevisions,
  onSaveEvaluation
}) => {
  if (!isOpen) return null;

  const enabledSubjects = subjects.filter(s => s.enabled !== false && !s.parentSubjectId);
  const defaultSubjectId = initialEvaluation?.subjectId || enabledSubjects[0]?.id || '';

  const [selectedSubjectId, setSelectedSubjectId] = useState<string>(defaultSubjectId);
  const [evalName, setEvalName] = useState<string>(initialEvaluation?.name || '');
  const [evalType, setEvalType] = useState<EvaluationType>(initialEvaluation?.type || 'prova');
  const [categoryName, setCategoryName] = useState<string>(
    initialEvaluation?.categoryName || (schoolConfig?.evalCategories || [])[0]?.name || 'Provas Principais (A1)'
  );
  const [evalDate, setEvalDate] = useState<string>(
    initialEvaluation?.date || new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0]
  );
  const [periodIndex, setPeriodIndex] = useState<number>(initialEvaluation?.periodIndex || 2);
  const [maxScore, setMaxScore] = useState<number>(initialEvaluation?.maxScore || 10.0);
  const [weight, setWeight] = useState<number>(initialEvaluation?.weight || 0.7);
  const [selectedTopicIds, setSelectedTopicIds] = useState<string[]>(initialEvaluation?.coveredTopics || []);
  const [autoGeneratePlan, setAutoGeneratePlan] = useState<boolean>(true);

  // Auto-preselect topics for the selected subject and period when subject changes or on initial open
  useEffect(() => {
    if (initialEvaluation) {
      setSelectedTopicIds(initialEvaluation.coveredTopics || []);
      return;
    }

    const primarySubject = subjects.find(s => s.id === selectedSubjectId);
    if (!primarySubject) return;

    // Collect topics from primary subject and subdivisions
    const relatedSubjects = subjects.filter(
      s => s.id === selectedSubjectId || s.parentSubjectId === selectedSubjectId
    );

    const periodTopics = relatedSubjects.flatMap(sub =>
      (sub.topics || []).filter(t => !t.bimester || t.bimester === periodIndex)
    );

    setSelectedTopicIds(periodTopics.map(t => t.id));
  }, [selectedSubjectId, periodIndex, initialEvaluation]);

  // Sync category weight when category changes
  const handleCategoryChange = (catName: string) => {
    setCategoryName(catName);
    const catObj = (schoolConfig.evalCategories || []).find(c => c.name === catName);
    if (catObj) {
      setMaxScore(catObj.maxScore || 10.0);
      setWeight(catObj.weightPercent ? catObj.weightPercent / 100 : 0.7);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!evalName.trim() || !selectedSubjectId) return;

    const evalId = initialEvaluation?.id || `eval-${Date.now()}`;

    const newEval: Evaluation = {
      id: evalId,
      subjectId: selectedSubjectId,
      periodIndex,
      name: evalName.trim(),
      categoryName,
      maxScore,
      weight,
      scoreObtained: initialEvaluation ? initialEvaluation.scoreObtained : null,
      date: evalDate,
      isRecovery: evalType === 'recuperacao',
      type: evalType,
      coveredTopics: selectedTopicIds,
      autoGeneratedPlan: autoGeneratePlan,
      reflectionText: initialEvaluation?.reflectionText,
      createdAt: initialEvaluation?.createdAt || new Date().toISOString()
    };

    let updatedTasks = existingTasks;
    let updatedRevisions = existingRevisions;

    if (autoGeneratePlan && selectedTopicIds.length > 0) {
      // Find subject & covered topic objects
      const primarySub = subjects.find(s => s.id === selectedSubjectId);
      if (primarySub) {
        const relatedSubs = subjects.filter(
          s => s.id === selectedSubjectId || s.parentSubjectId === selectedSubjectId
        );
        const coveredTopicObjs = relatedSubs.flatMap(s =>
          (s.topics || []).filter(t => selectedTopicIds.includes(t.id))
        );

        const plan = generateExamPrepPlan(
          newEval,
          coveredTopicObjs,
          primarySub,
          existingTasks,
          existingRevisions
        );

        updatedTasks = plan.updatedTasks;
        updatedRevisions = plan.updatedRevisions;
      }
    }

    trackEvent('evaluation_created', {
      evaluation_id: evalId,
      subject_id: selectedSubjectId,
      topics_count: selectedTopicIds.length,
      period_index: periodIndex,
      auto_generated_plan: autoGeneratePlan
    });

    onSaveEvaluation(newEval, updatedTasks, updatedRevisions);
    onClose();
  };

  return (
    <div className="fixed inset-0 bg-slate-950/70 backdrop-blur-sm z-50 flex items-center justify-center p-4 overflow-y-auto animate-in fade-in">
      <div className="bg-white rounded-3xl max-w-2xl w-full border border-slate-200 shadow-2xl overflow-hidden my-8">
        {/* Header */}
        <div className="bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 p-6 text-white flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="p-3 bg-indigo-500/20 rounded-2xl border border-indigo-400/30">
              <Sparkles className="w-6 h-6 text-amber-300" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <h3 className="text-lg font-bold font-display">
                  {initialEvaluation ? 'Editar Avaliação Inteligente' : 'Cadastrar Nova Avaliação Inteligente'}
                </h3>
                <span className="bg-indigo-500/30 text-indigo-200 text-[10px] font-extrabold px-2 py-0.5 rounded-full border border-indigo-400/30">
                  Vínculo Curricular
                </span>
              </div>
              <p className="text-xs text-slate-300 mt-0.5">
                Cadastre a prova para vincular automaticamente tópicos e gerar plano de revisão pré-prova.
              </p>
            </div>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="p-2 text-slate-400 hover:text-white rounded-xl hover:bg-slate-800 transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form Body */}
        <form onSubmit={handleSubmit} className="p-6 space-y-5 max-h-[80vh] overflow-y-auto">
          {/* Row 1: Subject + Type */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-extrabold text-slate-700 uppercase tracking-wider mb-1.5">
                Disciplina
              </label>
              <select
                value={selectedSubjectId}
                onChange={(e) => setSelectedSubjectId(e.target.value)}
                className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3.5 py-2.5 text-xs text-slate-900 font-bold focus:ring-2 focus:ring-indigo-500"
              >
                {enabledSubjects.map((sub) => (
                  <option key={sub.id} value={sub.id}>
                    {sub.name} ({sub.category})
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-xs font-extrabold text-slate-700 uppercase tracking-wider mb-1.5">
                Tipo de Avaliação
              </label>
              <select
                value={evalType}
                onChange={(e) => setEvalType(e.target.value as EvaluationType)}
                className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3.5 py-2.5 text-xs text-slate-900 font-bold focus:ring-2 focus:ring-indigo-500"
              >
                <option value="prova">Prova Bimestral/Trimestral</option>
                <option value="simulado">Simulado Modelo ENEM/Vestibular</option>
                <option value="teste">Teste / Quiz Rápido</option>
                <option value="recuperacao">Prova de Recuperação</option>
              </select>
            </div>
          </div>

          {/* Row 2: Name + Date */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="sm:col-span-2">
              <label className="block text-xs font-extrabold text-slate-700 uppercase tracking-wider mb-1.5">
                Nome da Avaliação
              </label>
              <input
                type="text"
                value={evalName}
                onChange={(e) => setEvalName(e.target.value)}
                placeholder="Ex: Prova A1 - Geometria Analítica e Matrizes"
                required
                className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3.5 py-2.5 text-xs text-slate-900 font-semibold focus:ring-2 focus:ring-indigo-500"
              />
            </div>

            <div>
              <label className="block text-xs font-extrabold text-slate-700 uppercase tracking-wider mb-1.5 flex items-center space-x-1">
                <Calendar className="w-3.5 h-3.5 text-indigo-600" />
                <span>Data da Prova</span>
              </label>
              <input
                type="date"
                value={evalDate}
                onChange={(e) => setEvalDate(e.target.value)}
                required
                className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3.5 py-2.5 text-xs text-slate-900 font-bold focus:ring-2 focus:ring-indigo-500"
              />
            </div>
          </div>

          {/* Row 3: Period + Category + Weight */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 p-4 bg-slate-50 rounded-2xl border border-slate-200">
            <div>
              <label className="block text-[11px] font-extrabold text-slate-600 uppercase tracking-wider mb-1">
                Período / Bimestre
              </label>
              <select
                value={periodIndex}
                onChange={(e) => setPeriodIndex(Number(e.target.value))}
                className="w-full bg-white border border-slate-300 rounded-xl px-3 py-2 text-xs text-slate-800 font-bold focus:ring-2 focus:ring-indigo-500"
              >
                {[1, 2, 3, 4].slice(0, schoolConfig.periodType === 'bimestre' ? 4 : 3).map((p) => (
                  <option key={p} value={p}>
                    {p}º {schoolConfig.periodType === 'bimestre' ? 'Bimestre' : 'Trimestre'}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-[11px] font-extrabold text-slate-600 uppercase tracking-wider mb-1">
                Categoria da Nota
              </label>
              <select
                value={categoryName}
                onChange={(e) => handleCategoryChange(e.target.value)}
                className="w-full bg-white border border-slate-300 rounded-xl px-3 py-2 text-xs text-slate-800 font-bold focus:ring-2 focus:ring-indigo-500"
              >
                {(schoolConfig.evalCategories || []).map((cat) => (
                  <option key={cat.id} value={cat.name}>
                    {cat.name} ({cat.weightPercent}%)
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-[11px] font-extrabold text-slate-600 uppercase tracking-wider mb-1">
                Valor Máximo / Peso
              </label>
              <div className="flex items-center space-x-2">
                <input
                  type="number"
                  step="0.1"
                  min="1"
                  max="100"
                  value={maxScore}
                  onChange={(e) => setMaxScore(parseFloat(e.target.value) || 10)}
                  className="w-20 bg-white border border-slate-300 rounded-xl px-2.5 py-2 text-xs text-slate-800 font-bold focus:ring-2 focus:ring-indigo-500 text-center"
                />
                <span className="text-xs text-slate-500 font-medium">pts</span>
              </div>
            </div>
          </div>

          {/* Topic Selector Section */}
          <TopicSelector
            subjects={subjects}
            selectedSubjectId={selectedSubjectId}
            selectedPeriodIndex={periodIndex}
            selectedTopicIds={selectedTopicIds}
            onChangeSelectedTopicIds={setSelectedTopicIds}
          />

          {/* Auto Plan Generation Toggle */}
          <div className="p-4 bg-gradient-to-r from-indigo-50 to-purple-50 border border-indigo-200 rounded-2xl flex items-center justify-between">
            <div className="flex items-start space-x-3">
              <div className="p-2 bg-indigo-600 text-white rounded-xl shrink-0 mt-0.5">
                <Sparkles className="w-5 h-5 text-amber-300" />
              </div>
              <div>
                <span className="text-xs font-extrabold text-indigo-950 block">
                  Plano de Revisão Inteligente Pré-Prova
                </span>
                <p className="text-[11px] text-slate-600 mt-0.5 leading-snug">
                  Gera tarefas de estudo distribuídas até a data da prova, insere os tópicos na repetição espaçada e cria simulados curtos de fixação.
                </p>
              </div>
            </div>

            <label className="relative inline-flex items-center cursor-pointer shrink-0 ml-3">
              <input
                type="checkbox"
                checked={autoGeneratePlan}
                onChange={(e) => setAutoGeneratePlan(e.target.checked)}
                className="sr-only peer"
              />
              <div className="w-11 h-6 bg-slate-300 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-slate-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-indigo-600"></div>
            </label>
          </div>

          {/* Submit Actions */}
          <div className="flex items-center justify-end space-x-3 pt-3 border-t border-slate-200">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-bold rounded-xl transition"
            >
              Cancelar
            </button>

            <button
              type="submit"
              className="px-6 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-extrabold rounded-xl shadow-md transition flex items-center space-x-2"
            >
              <Save className="w-4 h-4" />
              <span>{initialEvaluation ? 'Salvar Alterações' : 'Cadastrar Prova & Gerar Plano'}</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
