export type PeriodType = 'bimestre' | 'trimestre';
export type RecoveryType = 'bimestral' | 'semestral' | 'ambas' | 'nenhuma';
export type RecoveryCalc = 'substitutiva' | 'media';

export type ThemeId = 'modern-indigo' | 'warm-minimalist' | 'dark-focus' | 'academic-editorial';
export type LayoutDensity = 'default' | 'compact' | 'focus';
export type AppLayoutType = 'bento-grid' | 'sidebar-split' | 'focus-stream' | 'kanban-board';

export interface LayoutOption {
  id: AppLayoutType;
  name: string;
  subtitle: string;
  description: string;
}

export interface ThemeOption {
  id: ThemeId;
  name: string;
  subtitle: string;
  previewBg: string;
  previewCard: string;
  previewAccent: string;
  description: string;
}

export interface EvalCategoryConfig {
  id: string;
  name: string;
  weightPercent: number; // e.g. 70 for 70%
  maxScore: number; // e.g. 10.0
  description: string;
}

export interface SchoolConfig {
  periodType: PeriodType;
  passingScore: number; // e.g. 6.0
  maxScorePerPeriod: number; // e.g. 10.0
  recoveryType: RecoveryType;
  recoveryCalculation: RecoveryCalc;
  evalCategories: EvalCategoryConfig[];
}

export type HighSchoolSeries = '1st' | '2nd' | '3rd';
export type BimesterNumber = 1 | 2 | 3 | 4;

export interface CurriculumTopicTemplate {
  id: string;
  name: string;
  bimester: BimesterNumber;
}

export interface CurriculumSubjectTemplate {
  id: string;
  name: string;
  category: 'Exatas' | 'Humanas' | 'Biológicas' | 'Linguagens' | 'Redação' | 'Formação Geral' | 'Itinerário';
  color: string;
  topics: CurriculumTopicTemplate[];
}

export interface HighSchoolCurriculumTemplate {
  series: HighSchoolSeries;
  seriesLabel: string;
  subjects: CurriculumSubjectTemplate[];
}

export interface CurriculumConfigInfo {
  series: HighSchoolSeries;
  currentBimester: BimesterNumber;
  markPreviousAsCompleted: boolean;
  autoGenerated: boolean;
  templateVersion: string;
  updatedAt: string;
}

export interface TeacherTopic {
  id: string;
  name: string;
  taught: boolean;
  taughtDate?: string;
  bimester?: BimesterNumber;
  needsRecovery?: boolean;
  recoveryReason?: string;
}

export interface Subject {
  id: string;
  name: string;
  category: 'Exatas' | 'Humanas' | 'Biológicas' | 'Linguagens' | 'Redação' | 'Formação Geral' | 'Itinerário';
  color: string;
  teacherName?: string;
  topics: TeacherTopic[];
  examScopeTopicIds: string[]; // Selected for imminent revision
  enabled?: boolean; // toggle subject on/off
  isCustom?: boolean; // custom created subject
  weight?: number; // weight in period evaluation
  parentSubjectId?: string; // Reference if this subject is a subdivision of another subject
}

export interface GoogleDriveSyncInfo {
  isConfigured: boolean;
  studentGoogleAccount: string;
  parentEmails: string[];
  folderName: string; // "Estudei_EnsinoMedio_Data"
  folderId?: string;
  isSynced: boolean;
  lastSyncedAt?: string;
  connectedChildrenProfiles: Array<{
    id: string;
    studentName: string;
    studentYear: string;
    schoolName: string;
    guardianEmail: string;
    lastSyncedAt: string;
  }>;
  activeChildId: string;
}

export interface BookScanResult {
  bookTitle: string;
  publisher?: string;
  suggestedSubject: string;
  category: string;
  chapters: Array<{
    chapterNumber: number;
    chapterTitle: string;
    topics: string[];
  }>;
}

export type EvaluationType = 'prova' | 'simulado' | 'teste' | 'recuperacao';

export interface Evaluation {
  id: string;
  subjectId: string;
  periodIndex: number; // 1, 2, 3, 4
  name: string;
  categoryName: string;
  maxScore: number;
  weight: number; // multiplier or percentage
  scoreObtained: number | null; // null if pending
  date: string;
  isRecovery?: boolean;
  type?: EvaluationType;
  coveredTopics?: string[]; // IDs of TeacherTopic covered
  autoGeneratedPlan?: boolean;
  reflectionText?: string;
  createdAt?: string;
}

export interface StudySessionLog {
  id: string;
  subjectId: string;
  subjectName?: string;
  topic: string;
  minutes: number;
  date: string; // YYYY-MM-DD
  mode: 'escola' | 'enem';
  type?: DailyBlockType;
  autoTracked?: boolean;
  activityId?: string;
  dailyPlanBlockId?: string;
  questionsDone?: number;
  questionsCorrect?: number;
  timestamp?: string;
}

export interface QuestionLogEntry {
  id: string;
  subjectId: string;
  topic?: string;
  date: string; // YYYY-MM-DD
  totalQuestions: number;
  correctAnswers: number;
  wrongAnswers: number;
  accuracyRate: number; // 0 - 100 %
  source?: string;
  notes?: string;
  createdAt?: string;
}

export interface SpacedRevision {
  id: string;
  subjectId: string;
  topic: string;
  createdAt: string;
  steps: {
    days: 1 | 7 | 30 | number;
    dueDate: string;
    completed: boolean;
  }[];
  priority?: 'normal' | 'high' | 'critical';
  linkedEvaluationId?: string;
}

export interface StudentTaskItem {
  id: string;
  subjectId: string;
  title: string;
  type: 'prova' | 'trabalho' | 'tarefa' | 'lembrete' | 'projeto' | 'revision' | 'recovery' | 'quiz';
  date: string; // YYYY-MM-DD
  time?: string; // HH:mm
  priority: 'alta' | 'media' | 'normal' | 'low' | 'high' | 'critical';
  completed: boolean;
  notes?: string;
  syncedCalendar?: boolean;
  source?: 'manual' | 'msteams' | 'classroom' | 'scanner' | 'exam_plan' | 'recovery_plan';
  linkedEvaluationId?: string;
  topicId?: string;
  topicName?: string;
}

export interface SchoolPeriodItem {
  id: string;
  periodNumber: number; // 1º Período, 2º Período, etc.
  startTime: string; // e.g. "07:15"
  endTime: string;   // e.g. "08:00"
  subjectId: string;
}

export interface DaySchoolSchedule {
  dayKey: 'segunda' | 'terca' | 'quarta' | 'quinta' | 'sexta';
  dayName: string; // e.g. "Segunda-feira"
  periods: SchoolPeriodItem[];
}

export type SchoolTimetable = DaySchoolSchedule[];

export interface ParentGuardSettings {
  studentName: string;
  studentYear: string;
  schoolName: string;
  guardianEmail: string;
  lgpdAccepted: boolean;
  parentPin: string; // PIN for parent view confirmation
}

export interface UserProfile {
  uid: string;
  email: string;
  name: string;
  role: 'parent' | 'student';
  familyId: string;
  studentYear?: string;
  createdAt: string;
  photoURL?: string;
  // Monetization & Subscription Plan fields
  planType?: 'free' | 'pro_parent' | 'pro_student' | 'family_pass';
  subscriptionStatus?: 'active' | 'trial' | 'expired' | 'canceled';
  subscriptionValidUntil?: string;
  maxStudentsAllowed?: number;
}

export interface FamilyGroup {
  id: string;
  familyName: string;
  familyCode: string;
  parentUids: string[];
  studentUids: string[];
  createdAt: string;
}

export interface FamilyInvitation {
  id: string;
  familyId: string;
  familyCode: string;
  familyName: string;
  invitedEmail: string;
  targetRole: 'parent' | 'student';
  pinCode: string;
  status: 'pending' | 'accepted' | 'rejected' | 'expired';
  createdByUid: string;
  createdByName: string;
  createdAt: string;
  expiresAt: string;
}

export interface FamilyReward {
  id: string;
  familyId: string;
  studentUid: string;
  type: 'star' | 'medal_bronze' | 'medal_silver' | 'medal_gold' | 'trophy';
  title: string;
  message: string;
  realReward?: string;
  grantedByUid: string;
  grantedByName: string;
  trigger: 'auto_daily_goal' | 'manual' | 'challenge_winner' | 'agreement_milestone';
  createdAt: string;
  viewedByStudent: boolean;
}

export interface FamilyAuditLog {
  id: string;
  familyId: string;
  actorUid: string;
  actorName: string;
  action: 'invite_created' | 'invite_accepted' | 'member_removed' | 'profile_reset' | 'reward_granted';
  targetName?: string;
  details: string;
  timestamp: string;
}

export interface EssayCorrectionResult {
  totalScore: number;
  competencies: {
    number: number;
    name: string;
    score: number;
    feedback: string;
  }[];
  generalFeedback: string;
  strengths: string[];
  improvements: string[];
}

export interface NotebookOverviewResult {
  structuredSummary: string;
  keyConcepts: { term: string; definition: string }[];
  podcastScript: { speaker: string; line: string }[];
}

export interface FlashcardItem {
  id: string;
  question: string;
  answer: string;
  mnemonic?: string;
  subjectId: string;
  topic: string;
  difficultyRating?: 'facil' | 'medio' | 'dificil';
  lastReviewedAt?: string;
  nextReviewAt?: string;
  reviewCount?: number;
}

export interface FlashcardDeck {
  id: string;
  title: string;
  subjectId: string;
  category: string;
  cards: FlashcardItem[];
  createdAt: string;
}

export interface QuizQuestion {
  id: string;
  statement: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  subjectId: string;
  topic: string;
}

export interface QuizSession {
  id: string;
  subjectId: string;
  topic: string;
  questions: QuizQuestion[];
  userAnswers: Record<number, number>; // questionIndex -> chosenOptionIndex
  score: number;
  totalQuestions: number;
  completedAt: string;
}

export interface StudySummaryItem {
  id: string;
  title: string;
  subjectId: string;
  topic: string;
  formattedMarkdown: string;
  keyTakeaways: string[];
  audioText: string;
  podcastConversation?: { speaker: string; line: string }[];
  readingTimeMinutes: number;
  createdAt: string;
}

export interface SimuladoQuestion {
  id: string;
  statement: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  subjectId: string;
  area: 'Exatas' | 'Humanas' | 'Biológicas' | 'Linguagens' | 'Redação';
  topic: string;
}

export interface SimuladoExam {
  id: string;
  title: string;
  targetExam: 'ENEM' | 'FUVEST' | 'UNICAMP' | 'UNESP' | 'Geral';
  timeLimitMinutes: number;
  questions: SimuladoQuestion[];
  createdAt: string;
}

export interface SimuladoResult {
  id: string;
  examId: string;
  title: string;
  score: number;
  totalQuestions: number;
  correctAnswersCount: number;
  timeSpentSeconds: number;
  triEstimatedScore: number; // e.g. 780
  areaBreakdown: Record<string, { total: number; correct: number; percentage: number }>;
  completedAt: string;
}

export interface DiagnosticReport {
  id: string;
  studentUid: string;
  studentName: string;
  createdAt: string;
  overallScore: number; // 0 - 100
  learningPace: 'Acelerado' | 'Regular' | 'Inconstante' | 'Atencao Necessaria';
  atRiskTopics: Array<{
    subjectName: string;
    topicName: string;
    severity: 'alta' | 'media' | 'baixa';
    recommendation: string;
  }>;
  strengths: string[];
  fourWeekRevisionPlan: Array<{
    weekNumber: number;
    title: string;
    focusSubjects: string[];
    actionItems: string[];
  }>;
  pedagogicalAdviceForParents: string;
}

export interface FamilyAgreement {
  id: string;
  familyId: string;
  studentUid: string;
  dailyGoalMinutes: number; // e.g. 60
  parentNote?: string;
  studentNote?: string;
  status: 'pending_student' | 'active' | 'revised';
  parentAcceptedAt?: string;
  studentAcceptedAt?: string;
  createdAt: string;
  updatedAt: string;
  rewardIncentive?: string;
}

export interface FamilyChallenge {
  id: string;
  familyId: string;
  title: string;
  description: string;
  type: 'quiz_battle' | 'focus_time' | 'streak_master';
  targetMinutes?: number;
  targetStreakDays?: number;
  status: 'active' | 'completed' | 'draft';
  createdByUid: string;
  createdAt: string;
  endsAt: string;
  participants: Array<{
    studentUid: string;
    studentName: string;
    progressValue: number; // current focus minutes or streak days or quiz score
    completed: boolean;
    badgeEarned?: string;
  }>;
  rewardBadgeName: string;
}

// -------------------------------------------------------------
// PROMPT 1: MANUAL QUESTION VALIDATION & ANTI-CHEAT
// -------------------------------------------------------------
export type QuestionValidationMode = 'trust' | 'parent_approved' | 'ai_verified';
export type QuestionValidationStatus = 'pending' | 'approved' | 'rejected';

export interface ManualQuestionLog {
  id: string;
  studentUid: string;
  studentName?: string;
  subjectId: string;
  subjectName?: string;
  topic: string;
  date: string; // YYYY-MM-DD
  totalQuestions: number;
  correctAnswers: number;
  wrongAnswers: number;
  accuracyRate: number; // 0 - 100
  photoURL?: string;
  source?: string;
  notes?: string;
  validationMode: QuestionValidationMode;
  validationStatus: QuestionValidationStatus;
  validatedByUid?: string; // 'ai' or parent uid
  aiConfidence?: number; // 0-100
  aiEstimatedQuestions?: number;
  aiFeedback?: string;
  createdAt: string;
}

export interface ValidationSettings {
  mode: QuestionValidationMode;
  notifyOnSubmission: boolean;
  inconsistencyAlertEnabled: boolean;
}

// -------------------------------------------------------------
// PROMPT 2: CLASS GROUP RANKING, NICKNAMES & OLYMPIADS
// -------------------------------------------------------------
export type RankingCategory = 'hours' | 'questions' | 'accuracy' | 'streak' | 'simulations';
export type RankingPeriod = 'weekly' | 'monthly' | 'all_time';

export interface ClassGroup {
  id: string;
  name: string;
  createdByUid: string;
  createdByName?: string;
  inviteCode: string;
  categories: RankingCategory[];
  createdAt: string;
  isActive: boolean;
  memberCount: number;
}

export interface ClassMember {
  id: string;
  classId: string;
  uid: string; // private ID
  nickname: string;
  avatar: string; // emoji or illustration ID
  joinedAt: string;
  metrics: {
    weeklyHours: number;
    totalQuestions: number;
    accuracyRate: number;
    currentStreak: number;
    simulationsCompleted: number;
    trend?: 'up' | 'down' | 'stable';
  };
}

export interface OlympiadQuizQuestion {
  id: string;
  statement: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  topic: string;
}

export interface ClassOlympiad {
  id: string;
  classId: string;
  title: string;
  subjectId: string;
  subjectName: string;
  durationMinutes: number;
  questionCount: number;
  startDate: string;
  endDate: string;
  status: 'upcoming' | 'active' | 'finished';
  questions: OlympiadQuizQuestion[];
  createdByUid: string;
  results: Array<{
    memberUid: string;
    nickname: string;
    avatar: string;
    score: number;
    totalQuestions: number;
    timeSpentSeconds: number;
    completedAt: string;
  }>;
}

// -------------------------------------------------------------
// PROMPT 3: SMART CYCLE TIMER & ADAPTIVE CYCLE EXECUTION
// -------------------------------------------------------------
export type DailyBlockType = 'study' | 'exercises' | 'reading' | 'review' | 'revision' | 'questions' | 'flashcards' | 'quiz' | 'simulated' | 'free';

export interface CycleBlockItem {
  id: string;
  subjectId: string;
  subjectName: string;
  type: DailyBlockType;
  topicId?: string;
  topicName?: string;
  plannedMinutes: number;
  completed: boolean;
  actualMinutes?: number;
  questionsDone?: number;
  questionsCorrect?: number;
  selfRating?: number; // 1-5 stars
  fixated?: boolean; // For spaced revision feedback
  source: 'plan' | 'task' | 'spaced_revision' | 'teacher_diary' | 'manual';
  completedAt?: string;
  notes?: string;
  autoTracked?: boolean;
}

export type DailyPlanBlock = CycleBlockItem;

export interface CycleBreakItem {
  afterBlockIndex: number;
  plannedMinutes: number;
}

export type DailyPlanBreak = CycleBreakItem;

export interface DailyCycle {
  id: string;
  date: string; // YYYY-MM-DD
  blocks: CycleBlockItem[];
  breaks: CycleBreakItem[];
  totalPlannedMinutes: number;
  generatedAt: string;
  completedAt?: string;
  isCompleted?: boolean;
  isPerfectCycle?: boolean;
  isPerfectDay?: boolean;
}

export type DailyPlan = DailyCycle;




